# Generated by Django 2.0.4 on 2018-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180611_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
