# Generated by Django 2.0.4 on 2018-09-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
