# Generated by Django 2.0.4 on 2018-06-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
