# Generated by Django 2.0.4 on 2018-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.FileField(upload_to='profile_image'),
        ),
    ]
