# Generated by Django 2.0.4 on 2018-07-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
