# Generated by Django 2.0.4 on 2018-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180708_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='replies', to='home.Comment'),
        ),
    ]
