# Generated by Django 2.0.4 on 2018-07-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
